version: 2
jobs:
  build:
    working_directory: ~/graft
    parallelism: 1
    docker:
    - image: circleci/node:8.11.4-stretch

  steps:
    - run: curl -sSL https://get.haskellstack.org/ | sh
    - checkout
    - run: stack test
