version: 2
jobs:
  build:
    working_directory: ~/graft
    parallelism: 1
    docker:
    - image: circleci/node:8.11.4-stretch

    steps:
      - run: curl -sSL https://get.haskellstack.org/ | sh
      - checkout

      - restore_cache:
          keys:
          - cv-graft-cache-v1-dep-{{ .Branch }}-{{ checksum "stack.yml" }}-{{ checksum "graft.cabal" }}
          - cv-graft-cache-v1-dep-{{ .Branch }}-
          - cv-graft-cache-v1-dep-master-
          - cv-graft-cache-v1-dep-

      - run: stack test

      - save_cache:
          key: cv-graft-cache-v1-dep-{{ .Branch }}-{{ checksum "stack.yml" }}-{{ checksum "graft.cabal" }}
          paths:
          - "~/.stack"	
          - .stack-work
